<?php

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function render_form_mod_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['rend_content'] = array(
    'render element' => 'fieldset',
    'path' => drupal_get_path('module', 'render_form_mod') . '/templates',
    'template' => 'render-form-mod-content',
  );

  return $items;
}

/**
 * Implements hook_block_info().
 *
 * @return mixed
 */
function render_form_mod_block_info() {
  $blocks['render_form_mod'] = array(
    'info' => t('Rend FORM'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 * @return array
 */
function render_form_mod_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'render_form_mod':
      $block['subject'] = 'Rend Form';
      $block['content'] = drupal_get_form('render_form_mod_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function render_form_mod_preprocess_rend_content(&$variables) {
  if (!empty($variables['form']['render_form_mod_car_fuel'])) {
    $variables['form']['render_form_mod_car_fuel']['#weight'] = 10;
  }

  if (!empty($variables['form']['render_form_mod_brand'])) {
    $variables['form']['render_form_mod_brand']['#weight'] = 11;
  }
}

/**
 * Implements hook_form().
 *
 * @param $node
 * @param $form_state
 * @return array
 */
function render_form_mod_form($node, &$form_state) {
  $form = array();
  $form['carinfo'] = array(
    '#title' => t('Car Info'),
    '#description' => t('Add some info about the car'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    '#attributes' => array(
      'class' => array(
        'container-wrapper',
        'container-wrapper-class-2',
      ),
    ),

    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'render_form_mod') . '/css/styles.css',
      ),
      'js' => array(
        drupal_get_path('module', 'render_form_mod') . '/js/script-1.js',
        drupal_get_path('module', 'render_form_mod') . '/js/script-2.js',
      ),
    ),
    '#theme' => 'rend_content',
  );

  $form['carinfo']['render_form_mod_brand'] = array(
    '#title' => t('Car Brand'),
    '#type' => 'textfield',
    '#description' => t('Enter car brand'),
    '#default_value' => variable_get('render_form_mod_brand', 'Plymouth'),
    '#maxlength' => 255,
    '#size' => 16,
    '#attributes' => array(
      'placeholder' => t('Plymouth'),
      'class' => array(
        'brand-class',
      ),
    ),
    '#weight' => 1,
    '#required' => TRUE,
  );

  $form['carinfo']['render_form_mod_date'] = array(
    '#title' => t('Date'),
    '#type' => 'textfield',
    '#description' => t('Enter today\'s date'),
    '#default_value' => variable_get('render_form_mod_date', '01.01.2016'),
    '#maxlength' => 255,
    '#size' => 16,
    '#attributes' => array(
      'placeholder' => t('01.01.2016'),
      'class' => array(
        'date-class',
      ),
    ),
    '#element_validate' => array('render_form_mod_form_date_validate'),
    '#weight' => 9,
  );

  $form['carinfo']['render_form_mod_bargain'] = array(
    '#title' => t('It is possible to bargain'),
    '#type' => 'checkbox',
    '#weight' => 3,
    '#default_value' => variable_get('render_form_mod_bargain', 0),
    '#attributes' => array(
      'class' => array(
        'bargain-class',
      ),
    ),
  );

  $form['carinfo']['render_form_mod_country'] = array(
    '#type' => 'select',
    '#title' => t('Select country'),
    '#default_value' => variable_get('render_form_mod_country','usa'),
    '#options' => array(
      'usa' => 'USA',
      'german' => 'German',
      'japan' => 'Japan',
    ),
    '#description' => t('Choose a country.'),
    '#attributes' => array(
      'class' => array(
        'country-class',
      ),
    ),
    '#weight' => 2,
  );

  $form['carinfo']['render_form_mod_car_fuel'] = array(
    '#type' => 'radios',
    '#title' => t('Fuel type'),
    '#description' => t('When a poll is closed, visitors can no longer vote for it.'),
    '#default_value' => variable_get('render_form_mod_car_fuel','gasoline'),
    '#options' =>  array(
      'gasoline' => t('gasoline'),
      'diesel' => t('diesel'),
      'gas' => t('gas'),
      'electricity' => t('electricity'),
    ),
    '#attributes' => array(
      'class' => array(
        'fuel-class',
      ),
    ),
    '#weight' => 4,
  );

  $form['carinfo']['render_form_mod_car_description'] = array(
    '#title' => t('Description'),
    '#type' => 'textarea',
    '#description' => t('Add some description'),
    '#default_value' => variable_get('render_form_mod_car_description','The Plymouth Barracuda is a two-door car that was manufactured by Plymouth from the 1964 to 1974 model years.'),
    '#attributes' => array(
      'placeholder' => t('Plymouth Barracuda'),
      'class' => array(
        'description-class',
      ),
    ),
    '#weight' => 5,
    '#required' => TRUE,
  );

  $form['#attached']['css'] = array(
    drupal_get_path('module', 'render_form_mod') . '/css/styles.css',
  );

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'render_form_mod') . '/js/script-1.js',
    drupal_get_path('module', 'render_form_mod') . '/js/script-2.js',
  );

  $form['actions'] = array(
    '#type' => 'actions',
  );

  $form['actions']['render_form_mod_car_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Show with validation'),
    '#submit' => array(
      'render_form_mod_form_submit',
    ),
  );

  $form['actions']['render_form_mod_car_submit_another'] = array(
    '#type' => 'submit',
    '#value' => t('Show without validation'),
    '#submit' => array(
      'render_form_mod_form_submit',
    ),

    '#limit_validation_errors' => array(),
  );

  $form['#submit'][] = 'render_form_mod_form_submit_another';

  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function render_form_mod_form_submit($form, &$form_state) {
  $values = $form_state['input']['carinfo'];

  $is_bargain_possible = $values['render_form_mod_bargain'] ? ": it is possible to bargain. " : ": it isn't possible to bargain. ";
  $message_type = 'status';
  $from_country = ' from ' . $values['render_form_mod_country'];
  $fuel_type = ' with the ' . $values['render_form_mod_car_fuel'] . ' fuel type';
  $description = $values['render_form_mod_car_description'];
  $date = 'Today is the ' . $values['render_form_mod_date'] . '.';
  $message = t('@name @country @fuel @is_bargain_possible @description @date', array(
      '@name' => $values['render_form_mod_brand'],
      '@is_bargain_possible' => $is_bargain_possible,
      '@country' => $from_country,
      '@fuel' => $fuel_type,
      '@description' => $description,
      '@date' => $date)
  );

  $c = $values['render_form_mod_brand'];
  variable_set('render_form_mod_brand', $c);

  $c = $values['render_form_mod_bargain'];
  variable_set('render_form_mod_bargain', $c);

  $c = $values['render_form_mod_country'];
  variable_set('render_form_mod_country', $c);

  $c = $values['render_form_mod_date'];
  variable_set('render_form_mod_date', $c);

  $c = $values['render_form_mod_car_fuel'];
  variable_set('render_form_mod_car_fuel', $c);

  $c = $values['render_form_mod_car_description'];
  variable_set('render_form_mod_car_description', $c);

  drupal_set_message($message, $message_type);
}

function render_form_mod_form_submit_another($form, &$form_state) {
  $values = $form_state['input']['carinfo'];

  $name = 'This is a ' . $values['render_form_mod_brand'] . '!!!';
  $message_type = 'status';
  $message = t('@name', array(
      '@name' => $name)
  );

  $c = $values['render_form_mod_brand'];
  variable_set('render_form_mod_brand', $c);

  drupal_set_message($message, $message_type);
}

function render_form_mod_form_validate($form, &$form_state) {
  $brand = $form['carinfo']['render_form_mod_brand']['#value'];

  if (!preg_match('/^[a-z\s]+$/i',$brand)) {
    form_set_error(
      'carinfo][render_form_mod',
      t('The name of brand contains invalid characters')
    );
  }
}

function render_form_mod_form_date_validate($element, &$form_state) {
  $values = $element['#value'];

  if (isset($values) && !preg_match('/^[0-9]{2}.?[0-9]{2}.?[0-9]{4}$/',$values)) {
    form_set_error(
      'render_form_mod_date',
      t('The date format is invalid')
    );
  }
}

/**
 * Implements hook_form_alter().
 */
function render_form_mod_form_render_form_mod_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['actions']['render_form_mod_car_submit_another']['#submit']) && $form['#submit']) {
    $form['actions']['render_form_mod_car_submit_another']['#submit'] = array_merge($form['actions']['render_form_mod_car_submit_another']['#submit'], $form['#submit']);
    //$form['actions']['render_form_mod_car_submit_another']['#submit'][] = $form['#submit'][0];
  }
  //unset($form['carinfo']['render_form_mod_date']);
}
